import {FloatIBM} from 'gpc/floatIBM'
import {EBCDIC_TO_ASCII, ASCII_TO_EBCDIC} from 'gpc/ebcdic'



# HAL/S Runtime Error Groups (AERROR macro GROUP parameter)
SVC_ERROR_GROUPS = {
    1: "RUNTIME"
    2: "RUNTIME"
    3: "RUNTIME"
    4: "RUNTIME"
    5: "RUNTIME"
    6: "RUNTIME"
}

# HAL/S Runtime Error Messages (AERROR macro NUM parameter)
# Reconstructed from RUNASM source comments
SVC_ERROR_MESSAGES = {
    4:  "0 RAISED TO A POWER <= 0"
    5:  "NEGATIVE ARGUMENT FOR SQRT"
    6:  "EXPONENTIAL ARGUMENT TOO LARGE"
    7:  "LOG ARGUMENT <= 0"
    8:  "TRIG ARGUMENT TOO LARGE"
    9:  "HYPERBOLIC ARGUMENT TOO LARGE"
    10: "|ARGUMENT| > 1 FOR ACOS/ASIN"
    11: "TAN/COT ARGUMENT TOO LARGE"
    12: "TOO CLOSE TO SINGULARITY IN TAN/COT"
    15: "ROUND FUNCTION OVERFLOW"
    16: "SECOND ARGUMENT = 0 IN MOD/REM"
    17: "INDEX OUT OF RANGE"
    18: "NEGATIVE LENGTH IN LJUST/RJUST"
    19: "MOD/REM DOMAIN FAILURE"
    20: "CONVERSION ERROR"
    22: "CHARACTER-TO-INTEGER CONVERSION ERROR"
    24: "NEGATIVE BASE IN EXPONENTIATION"
    25: "DIVISION BY ZERO"
    27: "ARG OF INVERSE IS SINGULAR"
    28: "VECTOR/MATRIX DIVIDE BY ZERO"
    29: "ILLEGAL BIT STRING"
    30: "BIT POSITION OUT OF RANGE"
    31: "BIT-TO-OCTAL CONVERSION: INVALID CHARACTER"
    32: "BIT-TO-HEX CONVERSION: INVALID CHARACTER"
    33: "MOD GPC ERROR"
    59: "ACOSH ARGUMENT < 1"
    60: "ATANH |ARGUMENT| >= 1"
    62: "ATAN2 BOTH ARGUMENTS ZERO"
}

export class HalUCP
  # Emulate the HAL User Control Program
  #
  # The actual AP-101 hardware doesn't directly provide anything like
  # terminal/console I/O.  When running simulated on the 360, the
  # runtime provides READ & WRITE routines supported by the HalUCP
  # which monitors trap addresses to detect READ & WRITE calls.
  #
  # In the runtime IOINIT csect, IOCODE is written to to indicate
  # the operation, and IOBUF is used to send or receive data.
  # HalUCP monitors three addresses; INTRAP, OUTRAP, CNTRAP.
  # When any one of those addresses are executed HalUCP takes over
  # and performs the requested operation.
  #
  # HalUCP also intercepts SVC instructions:
  #   SVC 0         -> program halt (sets wait state)
  #   SVC AERROR    -> SEND ERROR (logs error, continues execution)
  #
  # This class is used from both the batch and interactive execution
  # loops.
  #
  # The I/O ops perform conversion to/from the GPC format in IOBUF.
  #
  # Strings may be in ASCII, EBCDIC or DEU format on the GPC.
  # Example HAL programs are in ASCII, so we're defaulting to that
  # for now.
  #
  constructor: (@cpu) ->
    @trapAddrs = null       # { outrap, intrap, cntrap }
    @iocodeAddr = null      # address of IOCODE halfword
    @iobufAddr = null       # address of IOBUF (129 halfwords)
    @waitingForInput = false
    @pendingIocode = null   # iocode that triggered input wait
    @outputCallback = null  # function(text, channel) called to emit output text
    @inputCallback = null   # function(channel, iocode) called to request input
    @controlCallback = null # function(iocode, param, channel) called for control ops
    @errorCallback = null   # function(msg) called for SVC error messages
    @trapSvcError = true    # intercept SEND ERROR SVCs instead of loading new PSW
    @svcTrapped = false     # set true when handleSVC intercepts; caller can check & clear
    @active = false
    @wasRunning = false     # whether we were in run() when input blocked
    @skipTrap = false       # set after provideInput so the trap instruction (BR R4) can execute
    @iobufEncoding = 'ebcdic'  # 'ebcdic' or 'ascii' — determined from symTypes
    @channel = 0            # current I/O channel (set by IOINIT)
    @inputBuffer = ''       # buffered comma-separated input text from multi-value entry

  # Handle an SVC instruction.  Returns true if the SVC was intercepted
  # (caller should skip the standard PSW swap), false otherwise.
  #
  # ea: effective address of the SVC operand
  # r1: contents of R1 (program data block pointer)
  #
  # SVC 0 (halt) is generated by %SVCI(0) as "SVC 0(R1)", so EA == R1.
  # SEND ERROR is generated by AERROR macro; EA points to ERRPARMS block
  # whose first halfword is 0x0014, second is (group<<8 | num).
  handleSVC: (ea, r1) ->
    return false unless @trapSvcError

    # Debug: dump EA, R1, and memory at EA
    hw0 = if ea >= 0 then @cpu.mainStorage.get16(ea) else 0
    hw1 = if ea >= 0 then @cpu.mainStorage.get16(ea + 1) else 0
    nia = @cpu.psw.getNIA()
    dbg = "SVC DEBUG: ea=0x#{ea.toString(16)} R1=0x#{r1.toString(16)} NIA=0x#{nia.toString(16)}" +
      " mem[ea]=0x#{hw0.toString(16).padStart(4,'0')} mem[ea+1]=0x#{hw1.toString(16).padStart(4,'0')}"
    process.stderr.write dbg + "\n"

    # SVC 0 — program halt: %SVCI(0) generates SVC 0(R1), so EA == upper 16 bits of R1.
    # g_EA computes the base from @r(b).get32() >>> 16, so EA is a halfword address
    # while r1 is the full 32-bit register value.
    if ea == (r1 >>> 16)
      if @inputBuffer.length > 0
        warnMsg = "HalUCP: WARNING: unconsumed buffered input: #{@inputBuffer}"
        if @errorCallback
          @errorCallback(warnMsg)
        else
          process.stderr.write warnMsg + "\n"
        @inputBuffer = ''
      msg = "HAL/S PROGRAM HALT (SVC 0)"
      if @errorCallback
        @errorCallback(msg)
      else
        process.stderr.write msg + "\n"
      @cpu.psw.setWaitState(true)
      @svcTrapped = true
      return true

    # SEND ERROR — ERRPARMS block at EA: first halfword 0x0014, second is descriptor
    svcCode = @cpu.mainStorage.get16(ea)
    if svcCode == 0x0014
      errDesc = @cpu.mainStorage.get16(ea + 1)
      errGroup = (errDesc >>> 8) & 0xff
      errNum = errDesc & 0xff
      groupName = SVC_ERROR_GROUPS[errGroup] ? "GROUP #{errGroup}"
      errMsg = SVC_ERROR_MESSAGES[errNum] ? "ERROR #{errNum}"
      msg = "HAL/S SEND ERROR: #{groupName}: ##{errNum} #{errMsg}"
      if @errorCallback
        @errorCallback(msg)
      else
        process.stderr.write msg + "\n"
      return true

    # Unknown SVC
    msg = "HAL/S SVC trapped (ea=0x#{ea.toString(16)}, R1=0x#{r1.toString(16)}, code=0x#{svcCode.toString(16)})"
    if @errorCallback
      @errorCallback(msg)
    else
      process.stderr.write msg + "\n"
    # DEBUG: stop on every SVC so we can inspect state
    @svcTrapped = true
    return true

  initFromSymbols: (symbols, symTypes) ->
    return unless symbols?.sections? and symbols?.symbols?

    # Find IOINIT section base address
    ioinitBase = null
    for sect in symbols.sections
      if sect.name == 'IOINIT'
        ioinitBase = sect.address
        break

    unless ioinitBase?
      process.stderr.write "HalUCP: IOINIT section not found in symbols\n"
      return

    # Find INTRAP entry address
    intrapAddr = null
    iocodeAddr = null
    iobufAddr = null
    for sym in symbols.symbols
      switch sym.name
        when 'INTRAP'
          intrapAddr = sym.address if sym.type == 'entry'
        when 'IOCODE'
          iocodeAddr = sym.address if sym.type == 'entry'
        when 'IOBUF'
          iobufAddr = sym.address if sym.type == 'entry'

    unless intrapAddr? and iocodeAddr? and iobufAddr?
      process.stderr.write "HalUCP: Missing required symbols (INTRAP=#{intrapAddr}, IOCODE=#{iocodeAddr}, IOBUF=#{iobufAddr})\n"
      return

    # These trap instructions don't have their own labels, but
    # since the code isn't gonna change we can just hardcode their
    # offsets;
    outrap = ioinitBase + 0x11 # in HOUT: BCR 0,0
    cntrap = ioinitBase + 0x40 # # BCR 7,4

    @trapAddrs = { outrap, intrap: intrapAddr, cntrap }
    @iocodeAddr = iocodeAddr
    @iobufAddr = iobufAddr

    # Determine IOBUF character encoding from symTypes
    # Check section-qualified key first, then bare name (same logic as watch pane)
    @iobufEncoding = 'ebcdic'
    if symTypes
      iobufSection = null
      for sect in symbols.sections
        if iobufAddr >= sect.address and iobufAddr < sect.address + sect.size
          iobufSection = sect.name
          break
      typeInfo = null
      if iobufSection
        typeInfo = symTypes["#{iobufSection}.IOBUF"]
      typeInfo ?= symTypes["IOBUF"]
      if typeInfo?.type == 'ascii'
        @iobufEncoding = 'ascii'

    @active = true

    process.stderr.write "HalUCP: Trap addresses resolved - OUTRAP=0x#{outrap.toString(16)}, INTRAP=0x#{intrapAddr.toString(16)}, CNTRAP=0x#{cntrap.toString(16)}\n"
    process.stderr.write "HalUCP: IOCODE=0x#{iocodeAddr.toString(16)}, IOBUF=0x#{iobufAddr.toString(16)}, encoding=#{@iobufEncoding}\n"

  isTrapAddr: (nia) ->
    return false unless @trapAddrs?
    if @skipTrap
      @skipTrap = false
      return false
    nia == @trapAddrs.outrap or nia == @trapAddrs.intrap or nia == @trapAddrs.cntrap

  checkTrap: (nia) ->
    return 'continue' unless @trapAddrs?

    if nia == @trapAddrs.outrap
      @handleOutput()
      return 'continue'
    else if nia == @trapAddrs.cntrap
      @handleControl()
      return 'continue'
    else if nia == @trapAddrs.intrap
      return @handleInput()
    else
      return 'continue'

  # Format integer for WRITE output: right-justified in a 6-character field,
  # no leading zeros, '-' for negative, space for positive sign position.
  formatInteger: (val) ->
    s = Math.abs(val).toString()
    sign = if val < 0 then '-' else ' '
    str = sign + s
    if str.length < 6
      str = ' '.repeat(6 - str.length) + str
    return str

  # Format scalar for WRITE output matching ETOC/DTOC format:
  #   SP: [sign]d.ddddddE[+-]dd   (14 chars, 7 significant digits)
  #   DP: [sign]d.dddddddddddddddE[+-]dd  (23 chars, 16 significant digits)
  formatScalar: (ibmFloat, sigDigits, totalWidth) ->
    v = ibmFloat.toFloat()
    if v == 0
      # Zero: ' 0.0' padded to totalWidth
      return (' 0.0' + ' '.repeat(Math.max(0, totalWidth - 5)))
    sign = if v < 0 then '-' else ' '
    av = Math.abs(v)
    # Compute decimal exponent: floor(log10(|v|))
    exp = Math.floor(Math.log10(av))
    # Mantissa normalized to d.ddd...
    mantissa = av / Math.pow(10, exp)
    # Guard against floating-point edge cases
    if mantissa >= 10
      mantissa /= 10
      exp += 1
    else if mantissa < 1 and mantissa > 0
      mantissa *= 10
      exp -= 1
    # Format mantissa digits: first digit, '.', then remaining digits
    fracDigits = sigDigits - 1
    mantissaStr = mantissa.toFixed(fracDigits)
    # Ensure exactly one digit before decimal point
    if mantissaStr.indexOf('.') != 1
      mantissaStr = mantissa.toFixed(fracDigits)
    # Format exponent: E[+-]dd
    expSign = if exp >= 0 then '+' else '-'
    expStr = 'E' + expSign + Math.abs(exp).toString().padStart(2, '0')
    return sign + mantissaStr + expStr

  handleOutput: () ->
    iocode = @cpu.mainStorage.get16(@iocodeAddr)
    text = ''

    switch iocode
      when 8  # BOUT - bit string
        len = @cpu.mainStorage.get16(@iobufAddr)
        bits = @get32(@iobufAddr + 1)
        # Format as binary string of specified length
        bitStr = (bits >>> 0).toString(2).padStart(32, '0')
        text = bitStr.substring(32 - len)
      when 9  # IOUT - int32
        val = @get32(@iobufAddr)
        # Sign-extend from 32-bit
        if val & 0x80000000
          val = val - 0x100000000
        text = @formatInteger(val)
      when 10 # HOUT - int16
        val = @cpu.mainStorage.get16(@iobufAddr)
        # Sign-extend from 16-bit
        if val & 0x8000
          val = val - 0x10000
        text = @formatInteger(val)
      when 11 # EOUT - float SP (IBM hex)
        w = @get32(@iobufAddr)
        f = FloatIBM.From32(w)
        text = @formatScalar(f, 7, 14)
      when 12 # DOUT - float DP (IBM hex)
        w1 = @get32(@iobufAddr)
        w2 = @get32(@iobufAddr + 2)
        f = FloatIBM.From64(w1, w2)
        text = @formatScalar(f, 16, 23)
      when 13 # COUT - character string
        text = @readCharString()
      else
        text = "[IOCODE=#{iocode}?]"

    text += ' '
    @outputCallback?(text, @channel)

  handleControl: () ->
    iocode = @cpu.mainStorage.get16(@iocodeAddr)
    param = @cpu.mainStorage.get16(@iobufAddr)

    switch iocode
      when 0, 1, 2, 3 # IOINIT - channel init (iocode=mode, param=device number)
        @channel = param
        if @controlCallback?
          @controlCallback(iocode, param, @channel)
        else
          @outputCallback?('\n', @channel)
      when 4  # LINE - emit newlines
        count = if param > 0 then param else 1
        if @controlCallback?
          @controlCallback(iocode, param, @channel)
        else
          @outputCallback?('\n'.repeat(count), @channel)
      when 5  # COLUMN - emit spaces to column
        if @controlCallback?
          @controlCallback(iocode, param, @channel)
        else
          @outputCallback?(' '.repeat(Math.max(0, param)), @channel)
      when 6  # TAB - emit tab spaces (count * 5)
        count = if param > 0 then param else 1
        if @controlCallback?
          @controlCallback(iocode, param, @channel)
        else
          @outputCallback?(' '.repeat(count * 5), @channel)
      when 7  # PAGE - page break
        if @controlCallback?
          @controlCallback(iocode, param, @channel)
        else
          @outputCallback?('\n--- PAGE ---\n', @channel)
      when 8  # SKIP - blank lines
        count = if param > 0 then param else 1
        if @controlCallback?
          @controlCallback(iocode, param, @channel)
        else
          @outputCallback?('\n'.repeat(count), @channel)
      else
        process.stderr.write "HalUCP: Unknown control IOCODE=#{iocode}\n"

  handleInput: () ->
    iocode = @cpu.mainStorage.get16(@iocodeAddr)

    # If we have buffered text from a previous comma-separated entry, consume from it
    if @inputBuffer.length > 0
      if iocode == 13  # CHARACTER - consume entire remaining buffer
        item = @inputBuffer
        @inputBuffer = ''
      else  # Numeric - consume up to next comma
        commaIdx = @inputBuffer.indexOf(',')
        if commaIdx >= 0
          item = @inputBuffer.substring(0, commaIdx).trim()
          @inputBuffer = @inputBuffer.substring(commaIdx + 1).trimStart()
        else
          item = @inputBuffer.trim()
          @inputBuffer = ''
      process.stderr.write "HalUCP: Input IOCODE=#{iocode} satisfied from buffer: \"#{item}\" (remaining: \"#{@inputBuffer}\")\n"
      @pendingIocode = iocode
      @_writeInputValue(item)
      @pendingIocode = null
      @skipTrap = true
      return 'continue'

    @waitingForInput = true
    @pendingIocode = iocode
    process.stderr.write "HalUCP: Input requested, IOCODE=#{iocode}\n"
    @inputCallback?(@channel, iocode)
    return 'block'

  provideInput: (text) ->
    return unless @waitingForInput

    if @pendingIocode == 13  # CHARACTER - use entire text, no comma splitting
      current = text
    else  # Numeric - split on first comma, buffer the rest
      commaIdx = text.indexOf(',')
      if commaIdx >= 0
        current = text.substring(0, commaIdx).trim()
        rest = text.substring(commaIdx + 1).trimStart()
        if rest.length > 0
          @inputBuffer = rest
      else
        current = text.trim()

    @_writeInputValue(current)

    @waitingForInput = false
    @pendingIocode = null
    @skipTrap = true  # let the trap instruction (BR R4) execute to return to caller

  # Write a single input value to IOBUF based on @pendingIocode
  _writeInputValue: (text) ->
    switch @pendingIocode
      when 8  # BIN - bit string
        # Parse binary string, write 32-bit value directly at IOBUF[0]
        bits = parseInt(text.replace(/[^01]/g, ''), 2) or 0
        @set32(@iobufAddr, bits >>> 0)
      when 9  # IIN - int32
        val = parseInt(text, 10) or 0
        # Convert to unsigned 32-bit representation
        if val < 0
          val = val + 0x100000000
        @set32(@iobufAddr, val >>> 0)
      when 10 # HIN - int16
        val = parseInt(text, 10) or 0
        if val < 0
          val = val + 0x10000
        @cpu.mainStorage.set16(@iobufAddr, val & 0xFFFF)
      when 11 # EIN - float SP (IEEE -> IBM hex)
        fval = parseFloat(text) or 0.0
        f = new FloatIBM(fval)
        @set32(@iobufAddr, f.to32())
      when 12 # DIN - float DP (IEEE -> IBM hex)
        fval = parseFloat(text) or 0.0
        f = new FloatIBM(fval)
        @set32(@iobufAddr, f.to64x())
        @set32(@iobufAddr + 2, f.to64y())
      when 13 # CIN - character string
        @writeCharString(text)
      else
        process.stderr.write "HalUCP: Unknown input IOCODE=#{@pendingIocode}\n"

  # Helper: read 32-bit value from two consecutive halfwords
  get32: (addr) ->
    hi = @cpu.mainStorage.get16(addr)
    lo = @cpu.mainStorage.get16(addr + 1)
    return ((hi << 16) | lo) >>> 0

  # Helper: write 32-bit value as two consecutive halfwords
  set32: (addr, val) ->
    @cpu.mainStorage.set16(addr, (val >>> 16) & 0xFFFF)
    @cpu.mainStorage.set16(addr + 1, val & 0xFFFF)

  # Read character string from IOBUF
  # Format: first halfword = [maxlen:8][curlen:8], followed by packed bytes
  # Encoding depends on @iobufEncoding (determined from symTypes)
  readCharString: () ->
    descriptor = @cpu.mainStorage.get16(@iobufAddr)
    len = descriptor & 0xFF  # current length in low byte
    chars = []
    for i in [0...len]
      hwOffset = Math.floor(i / 2)
      hw = @cpu.mainStorage.get16(@iobufAddr + 1 + hwOffset)
      if i % 2 == 0
        byte = (hw >> 8) & 0xFF  # high byte
      else
        byte = hw & 0xFF         # low byte
      if @iobufEncoding == 'ascii'
        # AP-101S DEU encoding: ASCII except 0x00 = '"' and 0x16 = '_'
        if byte == 0x00
          chars.push('"')
        else if byte == 0x16
          chars.push('_')
        else if byte >= 0x20 and byte < 0x7F
          chars.push(String.fromCharCode(byte))
        else
          chars.push('.')
      else
        chars.push(EBCDIC_TO_ASCII[byte] or '?')
    return chars.join('')

  # Write character string to IOBUF
  # Format: first halfword = [maxlen:8][curlen:8], followed by packed bytes
  writeCharString: (text) ->
    descriptor = @cpu.mainStorage.get16(@iobufAddr)
    maxLen = (descriptor >> 8) & 0xFF  # max length in high byte
    len = if maxLen > 0 then Math.min(text.length, maxLen) else text.length
    # Preserve maxlen in high byte, set curlen in low byte
    @cpu.mainStorage.set16(@iobufAddr, (maxLen << 8) | (len & 0xFF))
    for i in [0...len] by 2
      if @iobufEncoding == 'ascii'
        # AP-101S DEU encoding: '"' → 0x00, '_' → 0x16
        hiByte = if text[i] == '"' then 0x00 else if text[i] == '_' then 0x16 else text.charCodeAt(i) & 0xFF
        loByte = if i + 1 >= len then 0x20 else if text[i+1] == '"' then 0x00 else if text[i+1] == '_' then 0x16 else text.charCodeAt(i + 1) & 0xFF
      else
        hiByte = ASCII_TO_EBCDIC[text[i]] or 0x40
        loByte = if i + 1 < len then (ASCII_TO_EBCDIC[text[i+1]] or 0x40) else 0x40
      @cpu.mainStorage.set16(@iobufAddr + 1 + Math.floor(i / 2), (hiByte << 8) | loByte)

  # Map iocode to human-readable type name (for input iocodes)
  @iocodeTypeName: (iocode) ->
    switch iocode
      when 8  then 'BIT'
      when 9  then 'INTEGER'
      when 10 then 'SHORT INTEGER'
      when 11 then 'SCALAR'
      when 12 then 'DOUBLE SCALAR'
      when 13 then 'CHARACTER'
      else "UNKNOWN(#{iocode})"

  # Validate that text is convertible to the type required by iocode.
  # Returns null if valid, or an error string if not.
  @validateInput: (text, iocode) ->
    switch iocode
      when 8  # BIT - binary string
        cleaned = text.replace(/[^01]/g, '')
        if cleaned.length == 0
          return "expected binary string (0s and 1s)"
        return null
      when 9  # INTEGER (32-bit)
        if not /^-?\d+$/.test(text.trim())
          return "expected integer"
        val = parseInt(text.trim(), 10)
        if val < -2147483648 or val > 2147483647
          return "integer out of 32-bit range"
        return null
      when 10 # SHORT INTEGER (16-bit)
        if not /^-?\d+$/.test(text.trim())
          return "expected integer"
        val = parseInt(text.trim(), 10)
        if val < -32768 or val > 32767
          return "integer out of 16-bit range"
        return null
      when 11, 12 # SCALAR / DOUBLE SCALAR
        if not isFinite(parseFloat(text.trim()))
          return "expected number"
        return null
      when 13 # CHARACTER
        return null  # any string is valid
      else
        return "unknown iocode #{iocode}"
